# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [6]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 1.76 -0.06  2.55  0.42 -0.75]
 [-1.48 -1.03 -3.66  2.06 -0.1 ]
 [-0.43  1.27 -1.22 -1.92 -0.6 ]]
 
[[-0.65 -0.23 -1.97 -0.82]
 [ 0.64  0.29  2.15  0.78]
 [ 0.58  0.48  2.48  0.62]
 [ 0.74 -3.44 -0.5   2.43]
 [-0.46 -1.08 -1.7  -0.22]
 [ 0.31  0.11  1.15  0.39]
 [-1.24  1.55 -1.44 -2.38]]


In [10]:
np.round(np.matmul(A, B), 2)

array([[ 1.76, -0.06,  2.55,  0.42, -0.75],
       [-1.48, -1.03, -3.66,  2.06, -0.1 ],
       [-0.43,  1.27, -1.22, -1.92, -0.6 ]])

# Using pytorch

In [11]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1,dtype=torch.float)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.6800, -1.2800, -1.0500, -0.2400, -1.2700],
        [ 4.2200, -3.5700,  4.2700, -2.2900,  1.0800],
        [ 0.4200,  1.0400,  0.1200,  2.7700,  1.9400]])
 
tensor([[ 0.3600,  1.1200,  1.2300,  0.8600,  0.0400,  1.6600,  1.6300],
        [-0.4700,  0.2400, -1.0100, -2.1900,  0.1000, -0.5200, -1.0600],
        [ 0.9100,  1.3600,  1.0400, -1.7100,  1.0300, -1.6700, -0.8100]],
       dtype=torch.float64)
 
tensor([[ 0.3600,  1.1200,  1.2300,  0.8600,  0.0400,  1.6600,  1.6300],
        [-0.4700,  0.2400, -1.0100, -2.1900,  0.1000, -0.5200, -1.0600],
        [ 0.9100,  1.3600,  1.0400, -1.7100,  1.0300, -1.6700, -0.8100]])


<ipython-input-11-77e9d51fd1ca>:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1  ,2)), print(' ')
